# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BLXUItRUrrJVlql1G9V1jaG_pStfeOKT
"""

# Initialize an empty list
my_list = []

my_list.append(10)
my_list.append(20)
my_list.append(30)
my_list.append(40)

# Insert the value 15 at the second position (index 1)
my_list.insert(1, 15)

# Extend the list with another list [50, 60, 70]
my_list.extend([50, 60, 70])


my_list.pop()

# Sort the list in ascending order
my_list.sort()

# Find and print the index of the value 30 in the list
index_of_30 = my_list.index(30)
print("The index of the value 30 in my_list is:", index_of_30)